#!/usr/bin/env node
// Submits the live sitemap's URLs to IndexNow (Bing, Yandex, Seznam, Naver and others; Google does
// not read IndexNow). The Deploy workflow runs it after a successful production deploy.
//
// The search engines check ownership by fetching /<key>.txt from the site, so the key is public
// and lives in web/public. The sitemap is read from the live site rather than the build, because
// /sitemap.xml is generated by the API from the projects in storage.
//
// Nothing here may fail a deploy. The site is already live when this runs, so every problem is
// logged as a workflow warning and the script exits 0.
import { readdirSync, readFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';

export const SITE = 'https://www.atlasrelay.org';
const ENDPOINT = 'https://api.indexnow.org/indexnow';
const PUBLIC_DIR = join(dirname(fileURLToPath(import.meta.url)), '..', 'web', 'public');
// IndexNow accepts at most 10,000 URLs in one request.
const BATCH = 10000;
const TIMEOUT_MS = 20000;
// A fresh deploy can take a moment to reach every edge, and the sitemap function may be cold.
const ATTEMPTS = 4;
const RETRY_DELAY_MS = 15000;

const log = (msg) => console.log(`[indexnow] ${msg}`);
// ::warning:: makes the line an annotation on the workflow run, so a skipped submission is visible.
const warn = (msg) => console.log(`::warning::[indexnow] ${msg}`);

/** The key is the name of the one 32-hex-digit .txt file in web/public, whose content is the key. */
export function findKey(dir = PUBLIC_DIR) {
  const files = readdirSync(dir).filter((f) => /^[0-9a-f]{32}\.txt$/.test(f));
  if (files.length !== 1) throw new Error(`expected one IndexNow key file in ${dir}, found ${files.length}`);
  const key = files[0].slice(0, -4);
  const content = readFileSync(join(dir, files[0]), 'utf8').trim();
  if (content !== key) throw new Error(`${files[0]} does not contain its own key`);
  return key;
}

export function extractLocs(xml) {
  return [...xml.matchAll(/<loc>([^<]+)<\/loc>/g)].map((m) =>
    m[1].trim().replace(/&apos;/g, "'").replace(/&quot;/g, '"').replace(/&lt;/g, '<').replace(/&gt;/g, '>').replace(/&amp;/g, '&'),
  );
}

async function fetchText(url) {
  let last = '';
  for (let attempt = 1; attempt <= ATTEMPTS; attempt++) {
    try {
      const res = await fetch(url, { signal: AbortSignal.timeout(TIMEOUT_MS), headers: { 'cache-control': 'no-cache' } });
      if (res.ok) return await res.text();
      last = `HTTP ${res.status}`;
    } catch (err) {
      last = err instanceof Error ? err.message : String(err);
    }
    log(`${url}: ${last} (attempt ${attempt}/${ATTEMPTS})`);
    if (attempt < ATTEMPTS) await new Promise((r) => setTimeout(r, RETRY_DELAY_MS));
  }
  throw new Error(`${url} did not load: ${last}`);
}

export async function submit({ site = SITE, key = findKey() } = {}) {
  const urls = extractLocs(await fetchText(`${site}/sitemap.xml`));
  if (urls.length === 0) {
    warn('the sitemap has no <loc> entries, skipping');
    return;
  }
  const host = new URL(site).host;
  const foreign = urls.filter((u) => new URL(u).host !== host);
  if (foreign.length > 0) {
    warn(`the sitemap lists ${foreign.length} URL(s) outside ${host}, skipping (first: ${foreign[0]})`);
    return;
  }
  const keyLocation = `${site}/${key}.txt`;
  // The engines fetch this file to verify the submission, so check it is live before sending.
  const served = (await fetchText(keyLocation)).trim();
  if (served !== key) {
    warn(`${keyLocation} does not serve the key, skipping`);
    return;
  }
  const batches = Math.ceil(urls.length / BATCH);
  for (let i = 0; i < urls.length; i += BATCH) {
    const urlList = urls.slice(i, i + BATCH);
    const label = `batch ${i / BATCH + 1}/${batches}`;
    try {
      const res = await fetch(ENDPOINT, {
        method: 'POST',
        headers: { 'content-type': 'application/json; charset=utf-8' },
        body: JSON.stringify({ host, key, keyLocation, urlList }),
        signal: AbortSignal.timeout(TIMEOUT_MS),
      });
      // 200 and 202 both mean accepted; 202 means the key is still being verified.
      if (res.ok) log(`${label}: HTTP ${res.status} (${urlList.length} URL(s), ${host})`);
      else warn(`${label}: HTTP ${res.status} (${urlList.length} URL(s), ${host}): ${(await res.text()).slice(0, 500)}`);
    } catch (err) {
      warn(`${label} failed: ${err instanceof Error ? err.message : String(err)}`);
    }
  }
}

if (process.argv[1] && import.meta.url === pathToFileURL(process.argv[1]).href) {
  try {
    await submit();
  } catch (err) {
    warn(`skipped: ${err instanceof Error ? err.message : String(err)}`);
  }
}
